apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster
provisioner: kubernetes.io/glusterfs
 parameters:
  resturl: "http://10.42.0.0:8080"
  restuser: "admin"
  restuserkey: "heketi-secret"
  restauthenabled: "false"
