---
# tasks file for checkme
  - name: this is a test for checking a machines id
    service:
      name: network
      state: started
    register: status_result
  - debug: var=status_result.state

  - name: restart network service
    service: 
      name: network
      state: restarted
    when: status_result.state == "started"

  - name: check if file is present
    stat:
      path: /var/tmp/touch.yml
    register: touchme_result

  - name: Creating touch.yml
    file:
      path: /var/tmp/touch.yml
      state: touch
      mode: 755
    when: touchme_result.stat.exists is defined and not touchme_result.stat.exists

