---
    - name: Check if user is using RHEL
      assert:
        that: "ansible_distribution == 'RedHat'"
    
    - name: Creating Docker Storage Configuration File
      copy:
        src: docker-storage-setup
        dest: "{{ dockercfg }}"
        owner: root
        group: root
        mode: 755
        
    - name: Check if docker-vg exists
      stat:
        path: /dev/{{ docker-vg }}
      register: dockervg_result

    - name: Check if docker pool LV exists
      command: lv display | grep docker-pool
      register: pool_result
        
    - name: Creating Docker thing Pools and Configuring storage for docker Containers
      command: "docker-storage-setup"
      when: dockervg_result.stat.exists == False or pool_result == false
