---
    - name: Check if user is using RHEL
      assert:
        that: "ansible_distribution == 'RedHat'"
    
    - name: Install Katello rpm for satellite registration
      yum:
        name: "https://{{sat_svr}}/pub/katello-ca-consumer-latest.noarch.rpm"
        state: installed
      ignore_erros: true
      
    - name: Subscribing to Satellite Openshift Content Channel
      redhat_subscription:
        state: present
        activationkey: "{{ akey }}"
        org_id: "{{ org }}"
      ignore_errors: true
     
    - name: Restart goferd
      service:
        name: goferd
        state: started
        enabled: true
        
    - name: Open ports required for dnsmasq and dns for OCP
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - 8053/udp
        - 8053/tcp
        - 53/udp
        - 53/tcp
        - 4789/udp
        - 443/udp
        - 8443/udp
 
    - name: Enable Repos Specific to OCP 3.5
      command: subscription-manager repos --enable="rhel--7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable"rhel-7-fast-datapath-rpms"
      
    - name: Update all hosts
      yum:
        name: '*'
        state: latest
        
    - name: Installing Dependencies for Openshift Container Platform
      yum:
        name:
          - wget
          - git
          - net-tools
          - bind-utils
          - iptables-services
          - bridge-utils
          - sos
          - psacct
          - atomic-openshift-utils
          - docker
          - NetworkManager
    
    - name: Creating Docker deamon file
      copy:
        src: docker
        dest: "{{ dockercfg }}"
        owner: root
        group: root
        mode: 0775
        
    - name: Enable docker service
      systemd:
        name: docker
        state: started
        enabled: True
        
    - name: Ensure NetworkManager Setting for dns is disabled
      copy:
        src: NetworkManager.conf
        dest: "{{ nm_conf }}"
        owner: root
        group: root
        mode: 0644
        
    - name: Restart NetworkManager
      systemd:
        name: NetworkManager
        state: restarted
        enabled: True
