---
- name: Install Pre-requisite package and configure Openshift Container Platform 3.6 Systems for install on Master Nodes
  hosts: ocp-master
  roles:
    - docker-storage
    - docker-service
    - firewall
    - networking
#    - satellite
#    - ocp_packages
    - selinux
