---
- name: Install Pre-requisite packages and configure Openshift Container PLaform 3.5 Systems for install on Compute Nodes
  hosts: ocp-node
  roles: 
    - firewall
    - docker-service
    - networking
    - ocp_packages
    - satellite
    - selinux
