---
- name: Install Pre-requisite packages and configure Openshift Container PLaform 3.5 Systems for install on Compute Nodes
  hosts: ocp-node
  roles: 
    - firewall
    - networking
    - satellite
    - ocp-packages
    - docker-service
