---
    - name: Check if user is using RHEL
      assert:
        that: "ansible_distribution == 'RedHat'"
    
    - name: Enable Repos Specific to OCP 3.6
      command: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-ose-3.6-rpms" --enable="rhel-7-server-extras-rpms" --enable"rhel-7-fast-datapath-rpms"
      
    - name: Installing Dependencies for Openshift Container Platform
      yum:
        name:
          - wget
          - git
          - net-tools
          - bind-utils
          - iptables-services
          - bridge-utils
          - sos
          - psacct
          - atomic-openshift-utils
          - docker
          - NetworkManage
          - bash-completion
          - kexec-tools
